#!/usr/bin/env bash
# shellcheck disable=SC1091
set -e

if [[ -z $GLOBALHOOKNOPULL ]]; then
    source "$(dirname "$0")"/lib/_git
    pull_hooks "$(dirname "$0")"
    source "$(dirname "$0")"/lib/_docker
    pull_docker
    # Re-run this script with GLOBALHOOKNOPULL set to continue
    exec env GLOBALHOOKNOPULL=1 "$0"
else
    source "$(dirname "$0")"/lib/_util
    run_local_pre_commit
    TTY='' && [[ -t 1 ]] && exec < /dev/tty && TTY="t"
    source "$(dirname "$0")"/lib/_docker
    docker run --cap-add=SYS_ADMIN -i$TTY --rm --env TERM="$TERM" --env ANSIBLE_ROLES_PATH=roles/services:roles/base:roles/contrib -v "$(pwd)":/repo:ro "$LINT_IMAGE" bash -c 'cd /repo; /lint/pre-commit.docker'
fi
