#!/usr/bin/env bash

export LINTERS+=('cfnlint')

cfnlint() {
    local lint_files
    if [[ $1 == "-f" ]]; then
        lint_files="$2"
    else
        local files="$1"
        local fpattern='\.(yml|yaml|json)$'
        lint_files="$(echo "$files" | grep -E "$fpattern" | xargs grep -l '"\?AWSTemplateFormatVersion"\?:' || true)"
    fi
    while read -r file; do
        if ! cfn-lint "$file" ; then
            fail "$file" cfn-lint
        fi
    done < <(echo "$lint_files" | sed '/^$/d')
}

cfnlint-describe() {
    echo "Lint Cloudformation files with cfn-lint"
}

export LINTERS+=('rainfmt')

rainfmt() {
    local lint_files
    if [[ $1 == "-f" ]]; then
        lint_files="$2"
    else
        local files="$1"
        local fpattern='\.(yml|yaml|json)$'
        lint_files="$(echo "$files" | grep -E "$fpattern" | xargs grep -l '"\?AWSTemplateFormatVersion"\?:' || true)"
    fi
    while read -r file; do
        if ! rain fmt -v "$file" ; then
            fail "$file" "rain fmt"
        fi
    done < <(echo "$lint_files" | sed '/^$/d')
}

rainfmt-describe() {
    echo "Lint Cloudformation files with rain fmt"
}

