#!/usr/bin/env bash

export LINTERS+=('golint')

golint() {
    local lint_files
    if [[ $1 == "-f" ]]; then
        lint_files="$2"
    else
        local files="$1"
        local fpattern='\.go$'
        lint_files="$(echo "$files" | grep -E "$fpattern" || true)"
    fi
    while read -r file; do
        if [[ $(gofmt -l "$file" | wc -l) -gt 0 ]]; then
            gofmt -d "$file"
            fail "$file" gofmt
        fi
    done < <(echo "$lint_files" | sed '/^$/d')
}

golint-describe() {
    echo "Lint golang sources with gofmt"
}
