#!/usr/bin/env bash

export LINTERS+=('rpmlnt')

rpmlnt() {
    local lint_files
    if [[ $1 == "-f" ]]; then
        lint_files="$2"
    else
        local files="$1"
        local fpattern='\.spec$'
        lint_files="$(echo "$files" | grep -E "$fpattern" || true)"
    fi
    while read -r file; do
        if grep -q '^Name:' "$file" && \
           grep -q '^Version:' "$file"
        then
           HOME=/tmp rpmlint "$file" || fail "$file" rpmlint
        fi
    done < <(echo "$lint_files" | sed '/^$/d')
}

rpmlnt-describe() {
    echo "Lint RPM .spec files with rpmlint"
}
