#!/usr/bin/env bash

export LINTERS+=('xmlint')

xmlint() {
    local lint_files
    if [[ $1 == "-f" ]]; then
        lint_files="$2"
    else
        local files="$1"
        local fpattern='\.xml$'
        lint_files="$(echo "$files" | grep -E "$fpattern" || true)"
    fi
    while read -r file; do
        xmllint -noout "$file" || fail "$file" xmllint
    done < <(echo "$lint_files" | sed '/^$/d')
}

xmlint-describe() {
    echo "Lint XML files with xmllint"
}
