#!/usr/bin/env bash

export LINTERS+=('nokeys')

nokeys() {
    if [[ $1 == "-f" ]]; then
        lint_err_files="$2"
        lint_warn_files=""
    else
        local files="$1"
        local fpattern='\.pem$|\.crt$|.key$|^id_'
        lint_err_files="$(echo "$files" | grep -E "$fpattern" || true)"
        lint_warn_files="$(echo "$files" | grep -vE "$fpattern" || true)"
    fi

    while read -r file; do
        if grep -qa 'PRIVATE KEY' "$file"; then
            echo "ERROR: 'PRIVATE KEY' string found in file $file !"
            fail "$file" secrets
        fi
    done < <(printf "%s" "$lint_err_files")
    while read -r file; do
        if grep -qa 'PRIVATE KEY' "$file"; then
            echo "WARNING: 'PRIVATE KEY' string found in file $file !"
        fi
    done < <(echo "$lint_warn_files" | sed '/^$/d')

    while read -r file; do
        if grep -qa 'AKIA' "$file"; then
            echo "ERROR: 'AKIA' AWS key string found in file $file !"
            fail "$file" secrets
        fi
    done < <(echo "$lint_err_files" | sed '/^$/d'; echo "$lint_warn_files" | sed '/^$/d')
}

nokeys-describe() {
    echo "Look for and error on or warn about secrets in files"
}
